apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: devtools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      securityContext:
        runAsUser: 200
        runAsGroup: 2000
        fsGroup: 2000
      containers:
        - name: nexus
          image: 'sonatype/nexus3:3.15.2'
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          #securityContext:
            #fsGroup: 200
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data-claim