apiVersion: v1
kind: Service
metadata:
  name: nexus-service-nodeport
  namespace: devtools
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8081'
spec:
  selector:
    app: nexus
    group: service
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      name: web
    - port: 8082
      targetPort: 8082
      nodePort: 30082
      name: docker-private
    - port: 8083
      targetPort: 8083
      nodePort: 30083
      name: dockerhub-proxy