apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-claim
  namespace: devtools
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
