apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-claim
  namespace: devtools
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi