apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data-volume
  namespace: devtools
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/D/kubernetes/volumes/nexus-data"
