kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            #config
            - name: PROVISIONER_NAME
              value: local/nfs
            - name: NFS_SERVER
              value: 192.168.22.22
            - name: NFS_PATH
              value: /var/opt/kubernetes/volumes
      volumes:
        - name: nfs-client-root
          nfs:
            #config
            server: 192.168.22.22
            path: /var/opt/kubernetes/volumes
